name:  MULTI STEP WORKFLOW

on:  
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest


    steps:
      - name:  1.Checkout Code
        uses: actions/checkout@v4

      - name:  2.Print Current Directory
        run: pwd

      - name:  3.List Files
        run: ls -la

      - name:  4.Print Current Date
        run: date
